import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { animate } from 'animejs'
import type { FactoryState, MachineId } from '../digitalTwin/types'

interface Props { state: FactoryState; selectedId: MachineId; onSelect: (id: MachineId) => void; bottleneckId?: MachineId }
const ids: MachineId[] = ['M1','M2','M3','M4','M5','M6']
const positions: Record<MachineId, THREE.Vector3> = { M1:new THREE.Vector3(-12,1,0), M2:new THREE.Vector3(-7,1,0), M3:new THREE.Vector3(-2,1,0), M4:new THREE.Vector3(3,1,0), M5:new THREE.Vector3(8,1,0), M6:new THREE.Vector3(13,1,0) }
const pathPoints = [new THREE.Vector3(-15,1,0),new THREE.Vector3(-12,1,0),new THREE.Vector3(-7,1,0),new THREE.Vector3(-2,1,0),new THREE.Vector3(3,1,0),new THREE.Vector3(8,1,0),new THREE.Vector3(13,1,0),new THREE.Vector3(16,1,0)]
function material(color: number, roughness = .55) { return new THREE.MeshStandardMaterial({ color, roughness, metalness: .08 }) }
function box(w:number,h:number,d:number,mat:THREE.Material) { return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat) }
function addMachine(group:THREE.Group, id:MachineId) {
  const shell = material(0xe6e7e0); const dark = material(0x27302c); const red = material(0xd84937); const glass = new THREE.MeshPhysicalMaterial({ color:0xdbe6df, transparent:true, opacity:.28, roughness:.15 })
  group.add(box(2.5,1.8,2.2,shell)); const top = box(2.1,.35,1.8,dark); top.position.y=1.12; group.add(top)
  const indicator = new THREE.Mesh(new THREE.SphereGeometry(.09,12,8),material(0xd84937)); indicator.position.set(-.92,.96,1.12); indicator.name='indicator'; group.add(indicator)
  if (id==='M1') { const vat = new THREE.Mesh(new THREE.CylinderGeometry(.72,.72,1.2,32),glass); vat.rotation.z=Math.PI/2; vat.position.y=.1; group.add(vat); const blade=new THREE.Mesh(new THREE.BoxGeometry(1.5,.12,.12),red); blade.name='moving'; blade.position.y=.1; group.add(blade) }
  if (id==='M2') { const drum=new THREE.Mesh(new THREE.CylinderGeometry(.78,.78,1.45,24),dark); drum.rotation.z=Math.PI/2; drum.name='moving'; group.add(drum); for(let i=0;i<5;i++){const granule=new THREE.Mesh(new THREE.SphereGeometry(.11,10,8),red);granule.position.set(-.7+i*.34,.1,(i%2)*.3-.15);group.add(granule)} }
  if (id==='M3') { const hopper=new THREE.Mesh(new THREE.ConeGeometry(.65,.9,4),red); hopper.position.y=1.15; hopper.rotation.y=Math.PI/4; group.add(hopper); const punch=box(.5,.65,.5,shell); punch.name='punch'; punch.position.y=.45; group.add(punch); const die=box(.7,.18,.7,red); die.name='die'; die.position.y=-.28; group.add(die) }
  if (id==='M4') { const pan=new THREE.Mesh(new THREE.CylinderGeometry(.88,.88,.35,32),glass); pan.rotation.x=Math.PI/2;pan.name='moving';pan.position.y=.05;group.add(pan); for(let i=0;i<3;i++){const nozzle=box(.1,.45,.1,red); nozzle.position.set(-.4+i*.4,.82,0);group.add(nozzle)} }
  if (id==='M5') { const beam=new THREE.Mesh(new THREE.BoxGeometry(.08,1.7,1.8),new THREE.MeshBasicMaterial({color:0xd84937,transparent:true,opacity:.3})); beam.name='beam';beam.position.y=.2;group.add(beam); const cam=box(.35,.35,.35,dark);cam.position.set(0,1.15,0);group.add(cam); }
  if (id==='M6') { const strip=box(2,.16,1.3,glass);strip.position.y=-.48;strip.name='moving';group.add(strip); for(let i=0;i<4;i++){const cavity=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.08,16),red);cavity.rotation.x=Math.PI/2;cavity.position.set(-.62+i*.42,-.32,0);cavity.name='cavity';group.add(cavity)} const foil=box(2,.12,1.35,shell);foil.name='foil';foil.position.y=.6;group.add(foil)}
  group.userData.machineId=id
}
function pointOnPath(progress:number) { const scaled=progress*(pathPoints.length-1); const index=Math.min(pathPoints.length-2,Math.floor(scaled)); return pathPoints[index]!.clone().lerp(pathPoints[index+1]!,scaled-index) }
export function FactoryScene3D({ state, selectedId, onSelect, bottleneckId }: Props) {
  const mount=useRef<HTMLDivElement>(null); const sceneRef=useRef<THREE.Scene | null>(null); const cameraRef=useRef<THREE.PerspectiveCamera | null>(null); const rendererRef=useRef<THREE.WebGLRenderer | null>(null); const groupsRef=useRef<Record<string,THREE.Group>>({}); const buffersRef=useRef<THREE.Mesh[][]>([]); const productRef=useRef<THREE.Mesh | null>(null); const initialIdRef=useRef(selectedId); const focusRef=useRef(false); const stateRef=useRef({state,selectedId,bottleneckId});
  if (selectedId !== initialIdRef.current) focusRef.current = true
  stateRef.current={state,selectedId,bottleneckId}
  useEffect(()=>{ if(!mount.current)return; const scene=new THREE.Scene();scene.background=new THREE.Color(0xe9e9e3);scene.fog=new THREE.Fog(0xe9e9e3,18,38);sceneRef.current=scene; const camera=new THREE.PerspectiveCamera(37,1,.1,100);camera.position.set(0,9,17);camera.lookAt(0,1,0);cameraRef.current=camera; const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.setSize(mount.current.clientWidth,mount.current.clientHeight);rendererRef.current=renderer;mount.current.appendChild(renderer.domElement)
    scene.add(new THREE.HemisphereLight(0xffffff,0xaaa9a0,2.1));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(-4,12,8);key.castShadow=true;scene.add(key);const floor=new THREE.Mesh(new THREE.PlaneGeometry(42,10),material(0xd5d7d0));floor.rotation.x=-Math.PI/2;floor.position.y=-.55;floor.receiveShadow=true;scene.add(floor)
    const rail=box(38,.12,.42,material(0x525a54));rail.position.set(0,-.35,0);scene.add(rail);ids.forEach(id=>{const group=new THREE.Group();group.position.copy(positions[id]!);addMachine(group,id);group.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true}});scene.add(group);groupsRef.current[id]=group});buffersRef.current=state.buffers.map((_buffer,index)=>Array.from({length:12},(_,pile)=>{const materialMesh=new THREE.Mesh(new THREE.SphereGeometry(.09,10,8),material(0xd58a4b));materialMesh.position.set(-9.5+index*5+((pile%4)-1.5)*.18,-.12+(Math.floor(pile/4))*.16,(pile%3-.9)*.18);materialMesh.visible=false;scene.add(materialMesh);return materialMesh}))
    const product=new THREE.Mesh(new THREE.SphereGeometry(.16,16,12),material(0xd84937));product.castShadow=true;scene.add(product);productRef.current=product
    const raycaster=new THREE.Raycaster();const pointer=new THREE.Vector2();const click=(event:MouseEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(Object.values(groupsRef.current),true)[0];const group=hit?.object.parent;const id=group?.userData.machineId as MachineId|undefined;if(id){onSelect(id);const target=positions[id]!;animate(camera.position,{x:target.x*.48,y:6.5,z:15,duration:900,ease:'out(4)'})}};renderer.domElement.addEventListener('click',click)
    let frame=0;const renderLoop=()=>{frame=requestAnimationFrame(renderLoop);const current=stateRef.current;const t=current.state.simulationTime;const rate=Math.max(.08,current.state.throughput/80);const progress=((t%12)/12)*rate;product.position.copy(pointOnPath(progress)); current.state.buffers.forEach((buffer,index)=>buffersRef.current[index]?.forEach((mesh,pile)=>{mesh.visible=pile<Math.ceil((buffer.quantity/Math.max(buffer.maxCapacity,1))*12)})); ids.forEach(id=>{const g=groupsRef.current[id]!;const machine=current.state.machines.find(m=>m.id===id)!;g.scale.setScalar(id===current.selectedId?1.12:1);g.position.y=1+(id===current.selectedId?Math.sin(frame*.025)*.025:0);g.traverse(obj=>{if(!(obj instanceof THREE.Mesh))return;const selected=id===current.selectedId; if(obj.name==='indicator') (obj.material as THREE.MeshStandardMaterial).color.set(selected?0xd84937:0x758078);if(obj.name==='moving'){obj.rotation.y+=.015*(machine.outputRate/Math.max(machine.capacityPerMinute,1));obj.rotation.z+=.008*(machine.outputRate/Math.max(machine.capacityPerMinute,1))}if(obj.name==='punch')obj.position.y=.45+Math.max(0,machine.utilization)*.25*Math.sin(frame*.035);if(obj.name==='beam')obj.visible=selected;if(obj.name==='foil')obj.position.y=.6+.18*Math.max(0,machine.utilization)*Math.sin(frame*.025);})});const overview=!focusRef.current;const target=overview?new THREE.Vector3(0,1,0):positions[current.selectedId]!;const desired=overview?new THREE.Vector3(0,13,55):new THREE.Vector3(target.x*.48,6.5,15);camera.position.lerp(desired,overview?.025:.035);camera.lookAt(target.x,1,0);renderer.render(scene,camera)};renderLoop();const resize=()=>{if(!mount.current)return;camera.aspect=mount.current.clientWidth/mount.current.clientHeight;camera.updateProjectionMatrix();renderer.setSize(mount.current.clientWidth,mount.current.clientHeight)};window.addEventListener('resize',resize);return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',resize);renderer.domElement.removeEventListener('click',click);renderer.dispose();mount.current?.removeChild(renderer.domElement);groupsRef.current={}}
  },[onSelect])
  return <div className="factory-3d" ref={mount}><div className="factory-3d-label"><span>CONNECTED FACTORY / PRODUCT PATH</span><strong>{state.throughput.toFixed(0)} UNITS / MIN</strong></div><div className="factory-3d-caption"><span>POWDER → GRANULES → TABLETS → PACK</span><span>{bottleneckId ? `BOTTLENECK / ${bottleneckId}` : 'LIVE MATERIAL JOURNEY'}</span></div></div>
}
