import { useCallback, useEffect, useState } from 'react'
import { useDigitalTwin } from '../hooks/useDigitalTwin'
import { useWhatIf } from '../hooks/useWhatIf'
import type { MachineId } from '../digitalTwin/types'
import type { ScenarioResult } from '../digitalTwin/scenarioEngine'
import { Continuous2DJourney } from './Continuous2DJourney'

const chapters: Array<[MachineId, string, string]> = [['M1', 'MIX', 'POWDER'], ['M2', 'GRANULATE', 'GRANULES'], ['M3', 'PRESS', 'TABLET'], ['M4', 'COAT', 'COATED'], ['M5', 'CHECK', 'INSPECTED'], ['M6', 'PACK', 'FINISHED']]
export function StoryExperience() {
  const twin = useDigitalTwin(); const [started, setStarted] = useState(false); const [activeId, setActiveId] = useState<MachineId>('M1')
  const machine = twin.factoryState.machines.find((item) => item.id === activeId) ?? twin.factoryState.machines[0]!
  const selectChapter = useCallback((id: MachineId) => setActiveId(id), [])
  const start = () => { setStarted(true); twin.start() }
  const replay = () => { twin.reset(); setStarted(true); twin.start() }
  useEffect(() => () => twin.pause(), [twin.pause])
  return <div className="motion-site"><header className="motion-header"><a href="#top" className="motion-logo">SI—02</a><span className="motion-subtitle">DIGITAL PRODUCTION TWIN</span><div className="motion-controls"><span>T+{twin.factoryState.simulationTime.toString().padStart(2, '0')} MIN</span>{started && <button onClick={twin.isRunning ? twin.pause : start}>{twin.isRunning ? 'PAUSE' : 'RESUME'}</button>}</div></header><main><section className="motion-hero" id="top"><div className="motion-intro"><p className="micro-label">ONE MATERIAL / SIX CHAPTERS</p><h1>FROM<br /><em>POWDER</em><br />TO PRODUCT.</h1><p>A tiny material journey through mix, press, coat, check, and pack.</p><button className="motion-start" onClick={started ? replay : start}>{started ? 'REPLAY JOURNEY →' : 'START JOURNEY →'}</button></div><Continuous2DJourney state={twin.factoryState} activeId={activeId} started={started} onStage={selectChapter} /></section><nav className="chapter-nav" aria-label="Journey chapters">{chapters.map(([id, verb, material]) => <button key={id} className={activeId === id ? 'active' : ''} onClick={() => selectChapter(id)}><b>{id}</b><strong>{verb}</strong><small>{material}</small></button>)}</nav><section className="motion-readout"><div><span className="micro-label">NOW IN MOTION</span><h2>{machine.stage.toUpperCase()}</h2></div><div className="motion-metrics"><span><b>{machine.outputRate.toFixed(0)}</b> UNITS / MIN</span><span><b>{Math.round(machine.utilization * 100)}%</b> LOAD</span><span><b>{machine.queue.toFixed(0)}</b> WAITING</span></div><p>{machine.status === 'DOWN' ? 'The material waits here.' : 'The material keeps moving through the line.'}</p></section><Experiment twin={twin} /></main><footer className="motion-footer"><span>SI—02</span><span>RAW MATERIAL → FINISHED PRODUCT</span><span>LIVE DIGITAL TWIN</span></footer></div>
}
function Experiment({ twin }: { twin: ReturnType<typeof useDigitalTwin> }) { const whatIf = useWhatIf(); const selected = twin.factoryState.machines.find((m) => m.id === whatIf.form.machineId); const baseline = selected?.capacityPerMinute ?? 80; const value = whatIf.form.scenarioType === 'capacity' ? Number(whatIf.form.newCapacity) || baseline : Number(whatIf.form.downtimeDuration) || 5; const run = () => whatIf.runScenarioAction(twin.factoryState, twin.liveHistory); return <section className="motion-experiment"><div><span className="micro-label">OPTIONAL EXPERIMENT</span><h2>What if<br /><em>the pace changes?</em></h2></div><div className="experiment-controls"><label>MACHINE<select value={whatIf.form.machineId} onChange={(e) => whatIf.setMachineId(e.target.value as MachineId)}>{twin.factoryState.machines.map((m) => <option key={m.id} value={m.id}>{m.id} / {m.stage}</option>)}</select></label><div className="mode-toggle"><button className={whatIf.form.scenarioType === 'capacity' ? 'active' : ''} onClick={() => whatIf.setScenarioType('capacity')}>CAPACITY</button><button className={whatIf.form.scenarioType === 'downtime' ? 'active' : ''} onClick={() => whatIf.setScenarioType('downtime')}>DOWNTIME</button></div><label className="range-label"><span>{whatIf.form.scenarioType === 'capacity' ? 'CAPACITY' : 'DURATION'} <b>{value}</b></span><input type="range" min={whatIf.form.scenarioType === 'capacity' ? 20 : 1} max={whatIf.form.scenarioType === 'capacity' ? 140 : 15} value={value} onChange={(e) => whatIf.form.scenarioType === 'capacity' ? whatIf.setNewCapacity(e.target.value) : whatIf.setDowntimeDuration(e.target.value)} /></label><button className="experiment-run" onClick={run}>RUN SCENARIO →</button></div>{whatIf.result && <ExperimentResult result={whatIf.result} />}</section> }
function ExperimentResult({ result }: { result: ScenarioResult }) { const d = result.delta; return <div className="experiment-result"><span>PRODUCTION <b>{d.production.toFixed(0)}</b></span><span>THROUGHPUT <b>{d.throughput.toFixed(0)}</b></span><span>WIP <b>{d.wip.toFixed(0)}</b></span></div> }
